### ISSUE TITLE
Support dumping collections

### ISSUE THREAD

**Issue by revital-weinblum** [lassevk/ObjectDumper#2]
Hi,
thank you for this great implementations. works great for me even for highly hierarchical and complex class. 
As part of dumping the object, we need to dump collections.
Is it possible to add a support for that? and release it as NuGet?
Many thanks,
Revital

**Comment by lassevk** [comment]
This, at least the part about collections, was fixed in the commits you made, I'm closing this issue, but watch out for new issues being opened up by me today that will fix the nuget package request and other stuff in the near future. The fact that someone uses my library means it warrants being pulled down from the shelf and given a new lease on life, so let's do it properly :)

**Comment by revital-weinblum** [comment]
thanks a lot!!
